### ISSUE TITLE
Failed to start the app

### ISSUE THREAD

**Issue by wangpin34** [OtakuRoom/OtakuRoom#2]
![image](https://github.com/OtakuRoom/OtakuRoom/assets/12655367/990f3b70-91d2-4d1a-ab58-7563027d8084)

version: latest
os: `windows 10`
reproducibility: `always`

**Comment by wenyue** [comment]
请升级使用最新的客户端，我们的官方网站是：https://www.otakuroom.top/

**Comment by wenyue** [comment]
如果还有问题，可以加入群组一对一沟通
Telegram: https://t.me/iamotakuroom
QQ group: 813015912

**Comment by OtakuRoom** [comment]
请升级最新客户端，如果仍然有问题，可以加入群组一对一沟通
Telegram: https://t.me/iamotakuroom
QQ group: 813015912

**Comment by OtakuRoom** [comment]
请升级最新客户端，如果任然有问题，可以加入群组一对一沟通
Telegram: https://t.me/iamotakuroom
QQ group: 813015912
