### ISSUE TITLE
下载问题

### ISSUE THREAD

**Issue by AnlaAnla** [OtakuRoom/OtakuRoom#4]
你的程序从微软商店无法安装，在主页使用在线安装时，提示“解析应用包时出错。”，点击离线安装，网站url中cn字段会不断增加，如“https://www.otakuroom.top/download/cn/cn/cn/cn/cn/cn/cn/cn/cn/cn/cn/cn/cn/cn/cn/cn/index.html”

**Comment by wenyue** [comment]
应该已经修复了，麻烦再试一下。
